### ISSUE TITLE
安装启动notebook报错：ERROR [main] boot.SpringApplication : Application run failed

### ISSUE THREAD

**Issue by gaohongfeng1977** [byzer-org/byzer-notebook#201]
#问题描述：
我在远端服务器安装了byzer 引擎 ALLinOne。
然后，在本地Ubuntu22.04版本下载解压了notebook1.2.3，并修改notebook.properties文件
##notebook.properties修改内容
notebook.database.type=mysql
notebook.database.ip=127.0.0.1
notebook.database.port=3306
notebook.database.name=notebook
notebook.database.username=gw00241401
notebook.database.password=****
notebook.user.home=/mlsql
notebook.url=http://localhost:9002
notebook.mlsql.engine-url=http://10.246.96.82:9003/
notebook.mlsql.engine-backup-url=http://localhost:9004
notebook.mlsql.auth-client=streaming.dsl.auth.client.DefaultConsoleClient

##启动notebook 报错如下
./bin/notebook.sh start
## notebook.log 内容
2024-05-09 10:48:15,538 INFO  [background-preinit] util.Version : HV000001: Hibernate Validator 6.0.14.Final
2024-05-09 10:48:15,776 INFO  [main] console.NotebookLauncher : Starting NotebookLauncher on gw00241401-pc with PID 223481 (/data/tools/byzer-notebook/lib/notebook-console.jar started by gw00241401 in /data/tools/byzer-notebook)
2024-05-09 10:48:15,776 INFO  [main] console.NotebookLauncher : The following profiles are active: test
2024-05-09 10:48:15,818 INFO  [main] context.AnnotationConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@37ceb1df: startup date [Thu May 09 10:48:15 CST 2024]; root of context hierarchy
2024-05-09 10:48:16,854 INFO  [main] config.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2024-05-09 10:48:17,500 INFO  [main] support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$39e5085a] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-05-09 10:48:17,972 INFO  [main] tomcat.TomcatWebServer : Tomcat initialized with port(s): 9002 (http)
2024-05-09 10:48:18 new Byzer Notebook process pid is 223481
2024-05-09 10:48:18,076 INFO  [localhost-startStop-1] context.ContextLoader : Root WebApplicationContext: initialization completed in 2265 ms
2024-05-09 10:48:18,362 INFO  [localhost-startStop-1] autoconfigure.DruidDataSourceAutoConfigure : Init DruidDataSource
2024-05-09 10:48:18,575 WARN  [localhost-startStop-1] pool.DruidDataSource : removeAbandoned is true, not use in production.
2024-05-09 10:48:18,909 INFO  [localhost-startStop-1] pool.DruidDataSource : {dataSource-1} inited
2024-05-09 10:48:19,186 INFO  [localhost-startStop-1] servlet.FilterRegistrationBean : Mapping filter: 'characterEncodingFilter' to: [/*]
2024-05-09 10:48:19,186 INFO  [localhost-startStop-1] servlet.FilterRegistrationBean : Mapping filter: 'webMvcMetricsFilter' to: [/*]
2024-05-09 10:48:19,187 INFO  [localhost-startStop-1] servlet.FilterRegistrationBean : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2024-05-09 10:48:19,187 INFO  [localhost-startStop-1] servlet.FilterRegistrationBean : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2024-05-09 10:48:19,187 INFO  [localhost-startStop-1] servlet.FilterRegistrationBean : Mapping filter: 'requestContextFilter' to: [/*]
2024-05-09 10:48:19,187 INFO  [localhost-startStop-1] servlet.FilterRegistrationBean : Mapping filter: 'UrlFilter' to urls: [/*]
2024-05-09 10:48:19,187 INFO  [localhost-startStop-1] servlet.FilterRegistrationBean : Mapping filter: 'httpTraceFilter' to: [/*]
2024-05-09 10:48:19,187 INFO  [localhost-startStop-1] servlet.ServletRegistrationBean : Servlet dispatcherServlet mapped to [/]
2024-05-09 10:48:20,543 INFO  [main] jpa.LocalContainerEntityManagerFactoryBean : Building JPA container EntityManagerFactory for persistence unit 'default'
2024-05-09 10:48:20,556 INFO  [main] util.LogHelper : HHH000204: Processing PersistenceUnitInfo [
	name: default
	...]
2024-05-09 10:48:20,613 INFO  [main] hibernate.Version : HHH000412: Hibernate Core {5.2.17.Final}
2024-05-09 10:48:20,614 INFO  [main] cfg.Environment : HHH000206: hibernate.properties not found
2024-05-09 10:48:20,647 INFO  [main] common.Version : HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
2024-05-09 10:48:21,043 INFO  [main] dialect.Dialect : HHH000400: Using dialect: org.hibernate.dialect.MySQL5Dialect
2024-05-09 10:48:21,388 WARN  [main] context.AnnotationConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.MappingException: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
2024-05-09 10:48:21,388 INFO  [main] pool.DruidDataSource : {dataSource-1} closing ...
2024-05-09 10:48:21,392 INFO  [main] pool.DruidDataSource : {dataSource-1} closed
2024-05-09 10:48:21,411 INFO  [main] logging.ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-05-09 10:48:21,413 ERROR [main] boot.SpringApplication : Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.MappingException: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1694)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1087)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:857)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:548)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1242)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1230)
	at io.kyligence.notebook.console.NotebookLauncher.main(NotebookLauncher.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.MappingException: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:402)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:377)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1753)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1690)
	... 24 more
Caused by: org.hibernate.MappingException: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:123)
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:77)
	at org.hibernate.metamodel.internal.MetamodelImpl.initialize(MetamodelImpl.java:129)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:300)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:462)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:892)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:57)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:390)
	... 28 more
Caused by: org.hibernate.HibernateException: Unable to instantiate default tuplizer [org.hibernate.tuple.entity.PojoEntityTuplizer]
	at org.hibernate.tuple.entity.EntityTuplizerFactory.constructTuplizer(EntityTuplizerFactory.java:91)
	at org.hibernate.tuple.entity.EntityTuplizerFactory.constructDefaultTuplizer(EntityTuplizerFactory.java:116)
	at org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:382)
	at org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:519)
	at org.hibernate.persister.entity.SingleTableEntityPersister.<init>(SingleTableEntityPersister.java:124)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:96)
	... 36 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.hibernate.tuple.entity.EntityTuplizerFactory.constructTuplizer(EntityTuplizerFactory.java:88)
	... 45 more
Caused by: java.lang.NullPointerException
	at javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:103)
	at javassist.util.proxy.DefineClassHelper.toClass3(DefineClassHelper.java:151)
	at javassist.util.proxy.DefineClassHelper.toClass2(DefineClassHelper.java:134)
	at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:95)
	at javassist.util.proxy.FactoryHelper.toClass(FactoryHelper.java:131)
	at javassist.util.proxy.ProxyFactory.createClass3(ProxyFactory.java:530)
	at javassist.util.proxy.ProxyFactory.createClass2(ProxyFactory.java:515)
	at javassist.util.proxy.ProxyFactory.createClass1(ProxyFactory.java:451)
	at javassist.util.proxy.ProxyFactory.createClass(ProxyFactory.java:422)
	at org.hibernate.proxy.pojo.javassist.JavassistProxyFactory.postInstantiate(JavassistProxyFactory.java:75)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.buildProxyFactory(PojoEntityTuplizer.java:162)
	at org.hibernate.tuple.entity.AbstractEntityTuplizer.<init>(AbstractEntityTuplizer.java:156)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.<init>(PojoEntityTuplizer.java:58)
	... 50 more
2024-05-09 11:17:31,163 INFO  [background-preinit] util.Version : HV000001: Hibernate Validator 6.0.14.Final
2024-05-09 11:17:31,413 INFO  [main] console.NotebookLauncher : Starting NotebookLauncher on gw00241401-pc with PID 9185 (/data/tools/byzer-notebook/lib/notebook-console.jar started by gw00241401 in /data/tools/byzer-notebook)
2024-05-09 11:17:31,414 INFO  [main] console.NotebookLauncher : The following profiles are active: test
2024-05-09 11:17:31,467 INFO  [main] context.AnnotationConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@37ceb1df: startup date [Thu May 09 11:17:31 CST 2024]; root of context hierarchy
2024-05-09 11:17:32,611 INFO  [main] config.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2024-05-09 11:17:33,282 INFO  [main] support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$39e5085a] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-05-09 11:17:33 new Byzer Notebook process pid is 9185
2024-05-09 11:17:33,780 INFO  [main] tomcat.TomcatWebServer : Tomcat initialized with port(s): 9002 (http)
2024-05-09 11:17:33,901 INFO  [localhost-startStop-1] context.ContextLoader : Root WebApplicationContext: initialization completed in 2444 ms
2024-05-09 11:17:34,170 INFO  [localhost-startStop-1] autoconfigure.DruidDataSourceAutoConfigure : Init DruidDataSource
2024-05-09 11:17:34,428 WARN  [localhost-startStop-1] pool.DruidDataSource : removeAbandoned is true, not use in production.
2024-05-09 11:17:34,774 INFO  [localhost-startStop-1] pool.DruidDataSource : {dataSource-1} inited
2024-05-09 11:17:35,043 INFO  [localhost-startStop-1] servlet.FilterRegistrationBean : Mapping filter: 'characterEncodingFilter' to: [/*]
2024-05-09 11:17:35,044 INFO  [localhost-startStop-1] servlet.FilterRegistrationBean : Mapping filter: 'webMvcMetricsFilter' to: [/*]
2024-05-09 11:17:35,044 INFO  [localhost-startStop-1] servlet.FilterRegistrationBean : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2024-05-09 11:17:35,044 INFO  [localhost-startStop-1] servlet.FilterRegistrationBean : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2024-05-09 11:17:35,044 INFO  [localhost-startStop-1] servlet.FilterRegistrationBean : Mapping filter: 'requestContextFilter' to: [/*]
2024-05-09 11:17:35,044 INFO  [localhost-startStop-1] servlet.FilterRegistrationBean : Mapping filter: 'UrlFilter' to urls: [/*]
2024-05-09 11:17:35,044 INFO  [localhost-startStop-1] servlet.FilterRegistrationBean : Mapping filter: 'httpTraceFilter' to: [/*]
2024-05-09 11:17:35,044 INFO  [localhost-startStop-1] servlet.ServletRegistrationBean : Servlet dispatcherServlet mapped to [/]
2024-05-09 11:17:36,021 INFO  [main] jpa.LocalContainerEntityManagerFactoryBean : Building JPA container EntityManagerFactory for persistence unit 'default'
2024-05-09 11:17:36,036 INFO  [main] util.LogHelper : HHH000204: Processing PersistenceUnitInfo [
	name: default
	...]
2024-05-09 11:17:36,106 INFO  [main] hibernate.Version : HHH000412: Hibernate Core {5.2.17.Final}
2024-05-09 11:17:36,107 INFO  [main] cfg.Environment : HHH000206: hibernate.properties not found
2024-05-09 11:17:36,140 INFO  [main] common.Version : HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
2024-05-09 11:17:36,673 INFO  [main] dialect.Dialect : HHH000400: Using dialect: org.hibernate.dialect.MySQL5Dialect
2024-05-09 11:17:37,098 WARN  [main] context.AnnotationConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.MappingException: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
2024-05-09 11:17:37,099 INFO  [main] pool.DruidDataSource : {dataSource-1} closing ...
2024-05-09 11:17:37,102 INFO  [main] pool.DruidDataSource : {dataSource-1} closed
2024-05-09 11:17:37,130 INFO  [main] logging.ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-05-09 11:17:37,131 ERROR [main] boot.SpringApplication : Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.MappingException: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1694)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1087)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:857)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:548)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1242)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1230)
	at io.kyligence.notebook.console.NotebookLauncher.main(NotebookLauncher.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.MappingException: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:402)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:377)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1753)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1690)
	... 24 more
Caused by: org.hibernate.MappingException: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:123)
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:77)
	at org.hibernate.metamodel.internal.MetamodelImpl.initialize(MetamodelImpl.java:129)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:300)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:462)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:892)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:57)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:390)
	... 28 more
Caused by: org.hibernate.HibernateException: Unable to instantiate default tuplizer [org.hibernate.tuple.entity.PojoEntityTuplizer]
	at org.hibernate.tuple.entity.EntityTuplizerFactory.constructTuplizer(EntityTuplizerFactory.java:91)
	at org.hibernate.tuple.entity.EntityTuplizerFactory.constructDefaultTuplizer(EntityTuplizerFactory.java:116)
	at org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:382)
	at org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:519)
	at org.hibernate.persister.entity.SingleTableEntityPersister.<init>(SingleTableEntityPersister.java:124)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:96)
	... 36 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.hibernate.tuple.entity.EntityTuplizerFactory.constructTuplizer(EntityTuplizerFactory.java:88)
	... 45 more
Caused by: java.lang.NullPointerException
	at javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:103)
	at javassist.util.proxy.DefineClassHelper.toClass3(DefineClassHelper.java:151)
	at javassist.util.proxy.DefineClassHelper.toClass2(DefineClassHelper.java:134)
	at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:95)
	at javassist.util.proxy.FactoryHelper.toClass(FactoryHelper.java:131)
	at javassist.util.proxy.ProxyFactory.createClass3(ProxyFactory.java:530)
	at javassist.util.proxy.ProxyFactory.createClass2(ProxyFactory.java:515)
	at javassist.util.proxy.ProxyFactory.createClass1(ProxyFactory.java:451)
	at javassist.util.proxy.ProxyFactory.createClass(ProxyFactory.java:422)
	at org.hibernate.proxy.pojo.javassist.JavassistProxyFactory.postInstantiate(JavassistProxyFactory.java:75)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.buildProxyFactory(PojoEntityTuplizer.java:162)
	at org.hibernate.tuple.entity.AbstractEntityTuplizer.<init>(AbstractEntityTuplizer.java:156)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.<init>(PojoEntityTuplizer.java:58)
	... 50 more

**Comment by allwefantasy** [comment]
看着是数据库连接问题：

1. 尝试 JDK8
2. 确认数据库配置信息正确。

**Comment by gaohongfeng1977** [comment]
切换成jdk8就解决了，谢谢！！
